### ISSUE TITLE
Error with rtsp 

### ISSUE THREAD

**Issue by juvasquezg** [horgh/videostreamer#1]
Hi @horgh ,

I ran the remux_example.c with rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov to test and I get

**Application provided invalid, non monotonically increasing dts to muxer in stream 1: 18750 >= 0**

```bash
Output #0, mp4, to 'file:/tmp/out.mp4':
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160, q=2-31
in: pts:0 pts_time:0 dts:0 dts_time:0 duration:1024 duration_time:0.0213333 stream_index:0
out: pts:0 pts_time:0 dts:0 dts_time:0 duration:1024 duration_time:0.0213333 stream_index:0
in: pts:18750 pts_time:0.208333 dts:18750 dts_time:0.208333 duration:3750 duration_time:0.0416667 stream_index:1
out: pts:18750 pts_time:0.208333 dts:18750 dts_time:0.208333 duration:3750 duration_time:0.0416667 stream_index:1
in: pts:0 pts_time:0 dts:0 dts_time:0 duration:3750 duration_time:0.0416667 stream_index:1
out: pts:0 pts_time:0 dts:0 dts_time:0 duration:3750 duration_time:0.0416667 stream_index:1
[mp4 @ 0x10f1ae0] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 18750 >= 0
```

Maybe is easy to resolve for you :)

Thank you so much.

**Comment by horgh** [comment]
Hi @juvasquezg! Thank you for reporting this!

I figured out a solution and pushed a fix in https://github.com/horgh/videostreamer/commit/734ccb6d6bb1bd35f67645c10cbd8118cd45133b.

I found that ffmpeg adjusts the output dts when it sees dts like this in the input, so I updated videostream to do the same.

I tested with the input stream you provided, and remux_example now works. Thanks for providing that!

I also noticed that videostreamer was complaining about stream indices (using your sample input), and updated so that the output stream index will always be correct. As you got past that issue given your output, I expect you figured that out as well?

Please let me know if you run into any more issues, or if this issue persists!

**Comment by juvasquezg** [comment]
Hi @horgh 

Thank you very much, you are a super hero of golang and ffmpeg.

Closed ;)
