### ISSUE TITLE
Compile problem Ubuntu 14.10

### ISSUE THREAD

**Issue by rukavina** [horgh/videostreamer#4]
Hello,
Compile on ubuntu produces error:

> could not determine kind of name for C.av_packet_clone
could not determine kind of name for C.av_packet_free
could not determine kind of name for C.av_packet_unref

I install packages: libavcodec-dev, libavutil-dev, libavformat-dev

Any idea what could be the issue?
Thanks!

**Comment by horgh** [comment]
It looks like that version of Ubuntu uses the ffmpeg fork [libav](https://en.wikipedia.org/wiki/Libav). There is an API difference - those functions aren't available in it. I've never tried building this with libav.

Both Ubuntu & Debian are back using ffmpeg rather than that fork. Also, Ubuntu stopped supporting that release in July 2015!

I'd recommend updating your Ubuntu. All newer supported versions use ffmpeg I believe, so you will probably have more success building this on them too.

If you are stuck on that version and want to build this, the first step would be look for replacements for those functions. Glancing through the API, we could probably use `av_dup_packet()` instead of `av_packet_clone()`. But yeah, I think using a recent version of ffmpeg would be better.

**Comment by rukavina** [comment]
Thanks for the thorough explanation! I'll try installing ffmpeg or upgrading ubuntu.
Regards

**Comment by charles-at-linknext** [comment]
First of all, I am so sorry to append comments on a closed issue, please accept my apology. I bumped into the same issue and here is how I resolved it.

1. set PKG_CONFIG_PATH variable (e.g. /ffmpeg_build/lib/pkgconfig)
2. remove following line in videostreamer.go
// #cgo LDFLAGS: -lavformat -lavdevice -lavcodec -lavutil
3. replace following line in videostreamer.go
// #cgo pkg-config: libavcodec
with
// #cgo pkg-config: libavcodec libavfilter libavutil libavdevice libavformat

Hope this helps. And many thanks to horgh for the videostreamer project!
