### ISSUE TITLE
compile error debian stretch

### ISSUE THREAD

**Issue by ok1mgj** [horgh/videostreamer#8]
Hello,

installing on debian stretch is not possible, because:
```
go get github.com/horgh/videostreamer
# github.com/horgh/videostreamer
work/src/github.com/horgh/videostreamer/videostreamer.go:346:14: could not determine kind of name for C.av_packet_clone
work/src/github.com/horgh/videostreamer/videostreamer.go:265:4: could not determine kind of name for C.av_packet_free
```
Any idea how to solve this issue?

**Comment by horgh** [comment]
That's strange. I use it on Stretch myself.

Someone reported a similar compilation error with an older version of Ubuntu that was still using libav, but Stretch should be back on ffmpeg.

I wonder if you have old libraries installed somehow. What does this command show for you? You'll need at least version 3.2 for the ffmpeg libraries.

```
dpkg -l|grep libavcod|grep ^ii
```

For me it shows:

```
will@snorri:~$ dpkg -l|grep libavcod|grep ^ii
ii  libavcodec-dev:amd64                  7:3.2.10-1~deb9u1                 amd64        FFmpeg library with de/encoders for audio/video codecs - development files
ii  libavcodec57:amd64                    7:3.2.10-1~deb9u1                 amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
```

**Comment by ok1mgj** [comment]
Hi, here is output:
```
~# dpkg -l|grep libavcod|grep ^ii
ii  libavcodec-dev:amd64                 10:3.3.6-dmo1+deb9u1              amd64        Library to encode decode multimedia streams - devel files
ii  libavcodec57:amd64                   10:3.3.6-dmo1+deb9u1              amd64        Library to encode decode multimedia streams - runtime files

```

**Comment by horgh** [comment]
It looks like you're using the packages from deb-multimedia.org. I tried using them as well and it still builds fine for me. Very strange.

I'm not sure what to suggest. One idea is to see if there's an old avcodec.h on your system somewhere, outside of packages. If that happened, we could be using it and it might be old enough to not have those functions.

Could you try this? It might take a while to run:

```
find /usr -name avcodec.h
```

For me it just shows one:

```
root@952347f73a3d:~/go/bin# find /usr -name avcodec.h                                         
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h
```

Other than that I'm a bit stumped unfortunately.

**Comment by ok1mgj** [comment]
Hi,
```
 find /usr -name avcodec.h
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h
/usr/local/include/libavfilter/avcodec.h
/usr/local/include/libavcodec/avcodec.h

```
And yes, You are right, i`v found  deb-multimedia in sources.
```
deb http://www.deb-multimedia.org stretch main non-free
```
i`ll try to remove this depository without breaking dependencies.

**Comment by horgh** [comment]
I personally wouldn't recommend deb-multimedia.org, but I think it is not the problem in this case, so you could leave that.

The presence of the headers in `/usr/local` indicates a separate ffmpeg (or possibly libav) install, possibly from running `make install` at some point. That is probably what the problem is. The build is finding this other version, likely out of date, and using it.

To fix this, the best thing to do would be to delete the installation that is under `/usr/local`. Unfortunately that is not easy to do as it sounds like this isn't installed via packages. If you could figure out what version it is, you could potentially download it again and run `make uninstall`. Alternatively you could look through what is in `/usr/local` and delete ffmpeg related files. Obviously that is going to be difficult. But cleaning up that unpackaged install would be the best bet.

Another solution might be to update `videostreamer` to have CFLAGS that would exclude any under `/usr/local`. I'm not sure how to do that offhand (you could look in the `gcc` manual assuming you're using `gcc`), and even if this worked, your system would still have the two versions of the libraries. You could set these CFLAGS in the `#cgo` comments in `videostreamer.go`.
